project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kostas-moschonas
      - text: bluesky
        href: https://bsky.app/profile/kosmosc.bsky.social

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

