project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Kostas Moschonas"
  navbar:
    right:
      - blog.qmd
      - text: bluesky
        href: https://bsky.app/profile/kosmosc.bsky.social
      - icon: github
        href: https://github.com/kostas-moschonas

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute: 
  freeze: auto

